# Generated by Django 5.0.7 on 2025-11-05 08:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Money', 'Money')], max_length=50, verbose_name='Asset Name')),
                ('asset_type', models.CharField(max_length=50, verbose_name='Asset Type')),
                ('unit_name', models.CharField(choices=[('gram', 'gram'), ('amount', 'amount')], max_length=10, verbose_name='Unit Name')),
                ('nationality', models.CharField(blank=True, default='', max_length=80, verbose_name='Nationality / Country')),
                ('asset_code', models.CharField(help_text='Short code such as USD, MYR, GOLD_24, SILVER, etc.', max_length=10, unique=True, verbose_name='Asset Code')),
                ('unit_price_usd', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price (USD)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_type', 'asset_code'],
                'indexes': [models.Index(fields=['asset_code'], name='app_asset_asset_c_577910_idx'), models.Index(fields=['asset_type'], name='app_asset_asset_t_b909b9_idx'), models.Index(fields=['name'], name='app_asset_name_7cb1c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Phone Number')),
                ('country', models.CharField(blank=True, default='', max_length=80, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='City')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('display_currency', models.ForeignKey(blank=True, help_text="Must point to an Asset with unit_name='amount'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_using_as_display_currency', to='app.asset')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('ADD', 'إضافة أصل'), ('WITHDRAW', 'سحب أصل'), ('ZAKAT_OUT', 'إخراج زكاة')], max_length=12, verbose_name='Transfer Type')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('transfer_date', models.DateTimeField(verbose_name='Transfer Date')),
                ('note', models.CharField(blank=True, default='', max_length=240, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='app.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-transfer_date', '-id'],
                'indexes': [models.Index(fields=['user', 'transfer_date'], name='app_transfe_user_id_b7fa83_idx'), models.Index(fields=['asset', 'transfer_type'], name='app_transfe_asset_i_fc9aac_idx')],
            },
        ),
    ]
