# Generated by Django 5.0.7 on 2025-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_full_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='bill',
            field=models.ImageField(blank=True, null=True, upload_to='bills/', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(choices=[('Gold', 'ذهب'), ('Silver', 'فضة'), ('Money', 'اموال')], max_length=50, verbose_name='Asset Name'),
        ),
    ]
